version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/health-fu-api
    ports:
      - "43001:3000"
    tty: true
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 43002:3306
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql
volumes:
  bundle:
  db:
